using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.Bank;
using Content.Shared.AWS.Economy.Bank.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Content.Client.AWS.Economy.Bank.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BankTransferUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<ulong, string>? TransferRequested;

    private EconomyBankATMAccountInfo? _bankAccount;
    private string _historyFilter = string.Empty;

    public BankTransferUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SetupMoneySpinBox(TransferAmountBox);
        SetupRecipientPrefixOptions();

        TransferAmountBox.ValueChanged += _ => RefreshTransferButton();
        TransferRecipientPrefixOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            RefreshTransferButton();
        };
        TransferRecipientNumberField.OnTextChanged += _ => RefreshTransferButton();
        TransferButton.OnPressed += _ =>
        {
            if (_bankAccount is null)
                return;

            TransferRequested?.Invoke((ulong) TransferAmountBox.Value, GetRecipientAccountId());
        };

        HistorySearchField.OnTextChanged += _ =>
        {
            _historyFilter = HistorySearchField.Text ?? string.Empty;
            RefreshHistory();
        };
        HistorySearchField.Editable = false;

        RefreshTransferButton();
        RefreshAccountInfo();
    }

    public void UpdateState(EconomyBankATMUserInterfaceState state)
    {
        _bankAccount = state.BankAccount;
        var hasAccount = _bankAccount is not null;
        HistorySearchField.Editable = hasAccount;

        if (!hasAccount && _historyFilter.Length > 0)
        {
            _historyFilter = string.Empty;
            HistorySearchField.Text = string.Empty;
        }

        RefreshTransferButton();
        RefreshAccountInfo();
        SetError(state.Error);
    }

    public void SetError(string? error)
    {
        ErrorLabel.Text = error ?? string.Empty;
    }

    private void RefreshTransferButton()
    {
        var isEnabled = _bankAccount is { } account &&
                        !account.Blocked &&
                        TransferAmountBox.Value > 0 &&
                        account.Balance >= (long) TransferAmountBox.Value &&
                        !string.IsNullOrWhiteSpace(GetRecipientAccountId());
        TransferButton.Disabled = !isEnabled;
    }

    private void RefreshAccountInfo()
    {
        AccountIdLabel.Text = _bankAccount?.AccountId ?? "-";
        AccountOwnerLabel.Text = _bankAccount?.AccountName ?? "-";
        AccountBalanceLabel.Text = _bankAccount?.Balance.ToString("N0") ?? "-";
        RefreshHistory();
    }

    private void SetupMoneySpinBox(SpinBox spinBox)
    {
        spinBox.IsValid = amount => amount >= 0 && _bankAccount is { } account && amount <= account.Balance;
    }

    private void RefreshHistory()
    {
        HistoryContainer.DisposeAllChildren();

        if (_bankAccount?.Logs is not { Count: > 0 } logs)
        {
            var emptyLabel = new RichTextLabel { HorizontalExpand = true };
            emptyLabel.SetMessage(Loc.GetString("economy-bank-atm-menu-history-empty"));
            HistoryContainer.AddChild(emptyLabel);
            return;
        }

        var filter = _historyFilter.Trim();
        var hasFilter = filter.Length > 0;

        foreach (var log in logs)
        {
            var timestamp = FormatLogTimestamp(log.Date);
            var entryText = Loc.GetString(
                "economy-bank-atm-menu-history-entry",
                ("time", timestamp),
                ("message", log.Text));

            if (hasFilter)
            {
                if (!timestamp.Contains(filter, StringComparison.OrdinalIgnoreCase) &&
                    !log.Text.Contains(filter, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }
            }

            var entryLabel = new RichTextLabel { HorizontalExpand = true };
            entryLabel.SetMessage(entryText);
            HistoryContainer.AddChild(entryLabel);
        }

        if (HistoryContainer.ChildCount == 0)
        {
            var noResultsLabel = new RichTextLabel { HorizontalExpand = true };
            noResultsLabel.SetMessage(Loc.GetString("economy-bank-atm-menu-history-empty-filtered"));
            HistoryContainer.AddChild(noResultsLabel);
        }
    }

    private static string FormatLogTimestamp(TimeSpan timestamp)
    {
        var totalHours = (int) Math.Floor(timestamp.TotalHours);
        return $"{totalHours:00}:{timestamp.Minutes:00}:{timestamp.Seconds:00}";
    }

    private void SetupRecipientPrefixOptions()
    {
        TransferRecipientPrefixOption.Clear();

        var prototypes = _prototypeManager
            .EnumeratePrototypes<EconomyBankAccountPrefixPrototype>()
            .OrderBy(p => p.Order)
            .ToList();

        if (prototypes.Count == 0)
        {
            TransferRecipientPrefixOption.AddItem(string.Empty);
            TransferRecipientPrefixOption.SetItemMetadata(0, string.Empty);
            TransferRecipientPrefixOption.SelectId(0);
            return;
        }

        var selectedIndex = 0;

        for (var i = 0; i < prototypes.Count; i++)
        {
            var proto = prototypes[i];
            var text = proto.DisplayLoc.HasValue
                ? Loc.GetString(proto.DisplayLoc.Value)
                : proto.Display ?? string.Empty;

            TransferRecipientPrefixOption.AddItem(text);
            TransferRecipientPrefixOption.SetItemMetadata(i, proto.Prefix);

            if (proto.IsDefault)
                selectedIndex = i;
        }

        TransferRecipientPrefixOption.SelectId(selectedIndex);
        RefreshTransferButton();
    }

    private string GetRecipientAccountId()
    {
        var selectedId = TransferRecipientPrefixOption.SelectedId;
        var prefix = selectedId >= 0
            ? TransferRecipientPrefixOption.GetItemMetadata(selectedId) as string ?? string.Empty
            : string.Empty;
        var number = TransferRecipientNumberField.Text?.Trim() ?? string.Empty;

        if (!string.IsNullOrEmpty(prefix) &&
            number.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
        {
            number = number[prefix.Length..];
        }

        return prefix + number;
    }
}

