using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardMasterTaskEntry : PanelContainer
{
    private readonly DepartmentRewardTaskEntry _taskEntry;

    public DepartmentRewardMasterTaskEntry()
    {
        RobustXamlLoader.Load(this);
        _taskEntry = new DepartmentRewardTaskEntry();
        TaskContainer.AddChild(_taskEntry);
    }

    public void UpdateState(DepartmentRewardMasterTaskState state)
    {
        DepartmentLabel.Text = state.DepartmentName;
        _taskEntry.UpdateState(state.Task, confirmEnabled: false, failEnabled: false, showActionButtons: false);
    }
}
