using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardConsoleWindow : FancyWindow
{
    private readonly DepartmentRewardConsoleBoundUserInterface _owner;

    public DepartmentRewardConsoleWindow(DepartmentRewardConsoleBoundUserInterface owner)
    {
        _owner = owner;
        RobustXamlLoader.Load(this);

        AuthEjectButton.OnPressed += _ => _owner.OnAuthEjectPressed();
    }

    public void UpdateState(DepartmentRewardConsoleState state)
    {
        DepartmentLabel.Text = state.DepartmentName;
        StatusLabel.Text = state.StatusText;
        AuthStatusLabel.Text = state.AuthorizationText;

        AuthEjectButton.Disabled = !state.CanEject;

        UpdateTasks(state.Tasks, state.ConfirmEnabled, state.FailEnabled);
        UpdateHistory(state.History);
    }

    private void UpdateTasks(List<DepartmentRewardTaskState> tasks, bool confirmEnabled, bool failEnabled)
    {
        TasksContainer.DisposeAllChildren();

        if (tasks.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-console-tasks-empty"));
            TasksContainer.AddChild(empty);
            return;
        }

        foreach (var task in tasks)
        {
            var entry = new DepartmentRewardTaskEntry();
            entry.UpdateState(task, confirmEnabled, failEnabled);
            entry.ConfirmPressed += _owner.OnConfirmPressed;
            entry.FailPressed += _owner.OnFailPressed;
            TasksContainer.AddChild(entry);
        }
    }

    private void UpdateHistory(List<DepartmentRewardHistoryEntry> history)
    {
        HistoryContainer.DisposeAllChildren();

        if (history.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-console-history-empty"));
            HistoryContainer.AddChild(empty);
            return;
        }

        foreach (var entry in history)
        {
            var label = new RichTextLabel { HorizontalExpand = true };
            var description = ResolveHistoryDescription(entry);
            var text = Loc.GetString("department-reward-console-history-entry",
                ("time", entry.TimeText),
                ("text", description));
            label.SetMessage(text);
            HistoryContainer.AddChild(label);
        }
    }

    private static string ResolveHistoryDescription(DepartmentRewardHistoryEntry entry)
    {
        var taskText = ResolveHistoryTaskTitle(entry);
        return entry.Type switch
        {
            DepartmentRewardHistoryEntryType.Completed => Loc.GetString(
                "department-reward-console-history-task-complete",
                ("task", taskText)),
            DepartmentRewardHistoryEntryType.Failed => Loc.GetString(
                "department-reward-console-history-task-failed",
                ("task", taskText),
                ("penalty", entry.Penalty ?? 0)),
            _ => entry.DescriptionFallback ?? taskText
        };
    }

    private static string ResolveHistoryTaskTitle(DepartmentRewardHistoryEntry entry)
    {
        if (!string.IsNullOrEmpty(entry.TaskTitleLocId))
            return Loc.GetString(entry.TaskTitleLocId);

        return entry.TaskTitleFallback ?? string.Empty;
    }
}
