using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardTaskEntry : PanelContainer
{
    public event Action? ConfirmPressed;
    public event Action? FailPressed;
    private static readonly Color QuestColor = Color.FromHex("#d7b071");
    private static readonly StyleBoxFlat LockedStyle = new()
    {
        BackgroundColor = Color.Black
    };

    private const float DefaultContentWidth = 420f;
    private float _contentWidth = DefaultContentWidth;
    private bool _autoContentWidth = true;

    public DepartmentRewardTaskEntry()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => ConfirmPressed?.Invoke();
        FailButton.OnPressed += _ => FailPressed?.Invoke();

        ApplyContentWidth();
    }

    public void UpdateState(DepartmentRewardTaskState task, bool confirmEnabled, bool failEnabled, bool showActionButtons = true)
    {
        var stageLabel = GetStageLabel(task.Stage);
        if (!task.Visible)
        {
            ButtonsContainer.Visible = false;
            StageTitleLabel.Visible = true;
            RewardLabel.Visible = false;
            DescriptionLabel.Visible = false;
            StatusLabel.Visible = true;

            var lockedMessage = new FormattedMessage();
            lockedMessage.AddText(stageLabel);
            StageTitleLabel.SetMessage(lockedMessage);

            StatusLabel.SetMessage(GetStatusText(task));
            PanelOverride = LockedStyle;
            return;
        }

        StageTitleLabel.Visible = true;
        RewardLabel.Visible = true;
        DescriptionLabel.Visible = true;
        StatusLabel.Visible = true;
        PanelOverride = null;

        var stageMessage = new FormattedMessage();
        stageMessage.PushColor(QuestColor);
        stageMessage.AddText($"{stageLabel}: ");
        var titleText = ResolveLocalizedText(task.TitleLocId, task.TitleFallback);
        stageMessage.AddMessage(FormattedMessage.FromMarkupPermissive(titleText));
        stageMessage.Pop();
        StageTitleLabel.SetMessage(stageMessage);

        RewardLabel.SetMessage(FormattedMessage.FromMarkupPermissive(GetRewardText(task)));
        var descriptionText = ResolveLocalizedText(task.DescriptionLocId, task.DescriptionFallback);
        DescriptionLabel.SetMessage(FormattedMessage.FromMarkupPermissive(descriptionText));

        if (task.Available)
        {
            if (showActionButtons)
            {
                ButtonsContainer.Visible = true;
                StatusLabel.Visible = false;
                ConfirmButton.Disabled = !confirmEnabled;
                FailButton.Disabled = !failEnabled;
            }
            else
            {
                ButtonsContainer.Visible = false;
                StatusLabel.Visible = true;
                var statusText = GetStatusText(task);
                StatusLabel.SetMessage(FormattedMessage.FromMarkup($"[color=#d7b071]{statusText}[/color]"));
            }
        }
        else
        {
            ButtonsContainer.Visible = false;
            StatusLabel.Visible = true;
            var statusColor = task.Completed ? "#7ed957" : "#b0b0b0";
            var statusText = GetStatusText(task);
            StatusLabel.SetMessage(FormattedMessage.FromMarkup($"[color={statusColor}]{statusText}[/color]"));
        }
    }

    protected override void Resized()
    {
        base.Resized();

        if (!_autoContentWidth)
            return;

        var width = Math.Max(PixelWidth - 16f, DefaultContentWidth);
        if (!MathHelper.CloseToPercent(width, _contentWidth))
        {
            _contentWidth = width;
            ApplyContentWidth();
        }
    }

    public void SetContentWidth(float width)
    {
        _autoContentWidth = false;
        _contentWidth = Math.Max(width, 0f);
        ApplyContentWidth();
    }

    private void ApplyContentWidth()
    {
        StageTitleLabel.MaxWidth = _contentWidth;
        RewardLabel.MaxWidth = _contentWidth;
        DescriptionLabel.MaxWidth = _contentWidth;
        StatusLabel.MaxWidth = _contentWidth;
    }

    private static string ResolveLocalizedText(string? locId, string? fallback)
    {
        if (!string.IsNullOrEmpty(locId))
            return Loc.GetString(locId);

        return fallback ?? string.Empty;
    }

    private static string GetStageLabel(DepartmentRewardStage stage)
    {
        return stage switch
        {
            DepartmentRewardStage.Start => Loc.GetString("department-reward-stage-start"),
            DepartmentRewardStage.Mid => Loc.GetString("department-reward-stage-mid"),
            DepartmentRewardStage.Late => Loc.GetString("department-reward-stage-late"),
            _ => stage.ToString()
        };
    }

    private static string GetRewardText(DepartmentRewardTaskState task)
    {
        if (task.RewardAmount > 0)
            return Loc.GetString("department-reward-console-reward-amount", ("amount", task.RewardAmount));

        return task.RewardFallback ?? string.Empty;
    }

    private static string GetStatusText(DepartmentRewardTaskState task)
    {
        return task.Status switch
        {
            DepartmentRewardTaskStatus.Completed => Loc.GetString("department-reward-stage-completed"),
            DepartmentRewardTaskStatus.Cooldown => Loc.GetString("department-reward-console-stage-unlocktime",
                ("time", task.UnlockStationTimeText ?? "--:--:--")),
            DepartmentRewardTaskStatus.WaitingPrevious => Loc.GetString("department-reward-stage-wait-previous"),
            _ => Loc.GetString("department-reward-stage-available")
        };
    }
}
