using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardTaskEntry : PanelContainer
{
    public event Action? ConfirmPressed;
    public event Action? FailPressed;
    private static readonly Color QuestColor = Color.FromHex("#d7b071");
    private static readonly StyleBoxFlat LockedStyle = new()
    {
        BackgroundColor = Color.Black
    };

    public DepartmentRewardTaskEntry()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => ConfirmPressed?.Invoke();
        FailButton.OnPressed += _ => FailPressed?.Invoke();
    }

    public void UpdateState(DepartmentRewardTaskState task, bool confirmEnabled, bool failEnabled)
    {
        if (!task.Visible)
        {
            ButtonsContainer.Visible = false;
            StageTitleLabel.Visible = true;
            RewardLabel.Visible = false;
            DescriptionLabel.Visible = false;
            StatusLabel.Visible = true;

            var lockedMessage = new FormattedMessage();
            lockedMessage.AddText(task.StageLabel);
            StageTitleLabel.SetMessage(lockedMessage);

            StatusLabel.SetMessage(task.StatusText);
            PanelOverride = LockedStyle;
            return;
        }

        StageTitleLabel.Visible = true;
        RewardLabel.Visible = true;
        DescriptionLabel.Visible = true;
        StatusLabel.Visible = true;
        PanelOverride = null;

        var stageMessage = new FormattedMessage();
        stageMessage.PushColor(QuestColor);
        stageMessage.AddText($"{task.StageLabel}: ");
        stageMessage.AddMessage(FormattedMessage.FromMarkupPermissive(task.Title));
        stageMessage.Pop();
        StageTitleLabel.SetMessage(stageMessage);

        RewardLabel.Text = task.RewardText;
        DescriptionLabel.SetMessage(task.Description);

        if (task.Available)
        {
            ButtonsContainer.Visible = true;
            StatusLabel.Visible = false;
            ConfirmButton.Disabled = !confirmEnabled;
            FailButton.Disabled = !failEnabled;
        }
        else
        {
            ButtonsContainer.Visible = false;
            StatusLabel.Visible = true;
#pragma warning disable RA0007
            var statusColor = task.Completed ? "#7ed957" : "#b0b0b0";
#pragma warning restore RA0007
            StatusLabel.SetMessage(FormattedMessage.FromMarkup($"[color={statusColor}]{task.StatusText}[/color]"));
        }
    }
}
