using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardConsoleWindow : FancyWindow
{
    private readonly DepartmentRewardConsoleBoundUserInterface _owner;
    private const float TaskTextMaxWidth = 360f;

    public DepartmentRewardConsoleWindow(DepartmentRewardConsoleBoundUserInterface owner)
    {
        _owner = owner;
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => _owner.OnConfirmPressed();
        FailButton.OnPressed += _ => _owner.OnFailPressed();
        AuthEjectButton.OnPressed += _ => _owner.OnAuthEjectPressed();
    }

    public void UpdateState(DepartmentRewardConsoleState state)
    {
        DepartmentLabel.Text = state.DepartmentName;
        StatusLabel.Text = state.StatusText;
        AuthStatusLabel.Text = state.AuthorizationText;

        AuthEjectButton.Disabled = !state.CanEject;
        ConfirmButton.Disabled = !state.ConfirmEnabled;
        FailButton.Disabled = !state.FailEnabled;

        UpdateTasks(state.Tasks);
        UpdateHistory(state.History);
    }

    private void UpdateTasks(List<DepartmentRewardTaskState> tasks)
    {
        TasksContainer.DisposeAllChildren();

        if (tasks.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-console-tasks-empty"));
            TasksContainer.AddChild(empty);
            return;
        }

        foreach (var task in tasks)
        {
            TasksContainer.AddChild(BuildTaskEntry(task));
        }
    }

    private Control BuildTaskEntry(DepartmentRewardTaskState task)
    {
        var panel = new PanelContainer();
        panel.AddStyleClass("LowDivider");

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
            SeparationOverride = 4
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4
        };
        header.AddChild(new Label
        {
            Text = task.StageLabel,
            StyleClasses = { "LabelBold" },
            ClipText = false
        });

        header.AddChild(new Label
        {
            Text = task.RewardText,
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            ClipText = false,
            HorizontalAlignment = HAlignment.Right
        });

        body.AddChild(header);

        var titleLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxSize = new Vector2(TaskTextMaxWidth, float.PositiveInfinity)
        };
        titleLabel.SetMessage($"[bold]{task.Title}[/bold]");
        body.AddChild(titleLabel);

        var description = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxSize = new Vector2(TaskTextMaxWidth, float.PositiveInfinity)
        };
        description.SetMessage(task.Description);
        body.AddChild(description);

        var statusLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            MaxSize = new Vector2(TaskTextMaxWidth, float.PositiveInfinity)
        };

#pragma warning disable RA0007
        var statusColor = task.Completed
            ? "#7ed957"
            : task.Available ? "#fdcb6e" : "#b0b0b0";
#pragma warning restore RA0007

        statusLabel.SetMessage(FormattedMessage.FromMarkup($"[color={statusColor}]{task.StatusText}[/color]"));
        body.AddChild(statusLabel);
        panel.AddChild(body);

        return panel;
    }

    private void UpdateHistory(List<DepartmentRewardHistoryEntry> history)
    {
        HistoryContainer.DisposeAllChildren();

        if (history.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-console-history-empty"));
            HistoryContainer.AddChild(empty);
            return;
        }

        foreach (var entry in history)
        {
            var label = new RichTextLabel { HorizontalExpand = true };
            var text = Loc.GetString("department-reward-console-history-entry",
                ("time", entry.TimeText),
                ("text", entry.Description));
            label.SetMessage(text);
            HistoryContainer.AddChild(label);
        }
    }
}
