using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.DepartmentRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.AWS.Economy.DepartmentRewards;

[GenerateTypedNameReferences]
public sealed partial class DepartmentRewardMasterConsoleWindow : FancyWindow
{
    private readonly List<RichTextLabel> _historyLabels = new();

    public DepartmentRewardMasterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        HistoryContainer.OnResized += OnHistoryContainerResized;
    }

    public void UpdateState(DepartmentRewardMasterConsoleState state)
    {
        UpdateTasks(state.Tasks);
        UpdateHistory(state.History);
    }

    private void UpdateTasks(List<DepartmentRewardMasterTaskState> tasks)
    {
        TasksContainer.DisposeAllChildren();

        if (tasks.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-master-console-empty"));
            TasksContainer.AddChild(empty);
            return;
        }

        foreach (var task in tasks)
        {
            var entry = new DepartmentRewardMasterTaskEntry();
            entry.UpdateState(task);
            TasksContainer.AddChild(entry);
        }
    }

    private void UpdateHistory(List<DepartmentRewardMasterHistoryEntry> history)
    {
        HistoryContainer.DisposeAllChildren();
        _historyLabels.Clear();

        if (history.Count == 0)
        {
            var empty = new RichTextLabel { HorizontalExpand = true };
            empty.SetMessage(Loc.GetString("department-reward-console-history-empty"));
            HistoryContainer.AddChild(empty);
            return;
        }

        foreach (var entry in history)
        {
            var label = new RichTextLabel { HorizontalExpand = true };
            var description = ResolveHistoryDescription(entry.Entry);
            var text = Loc.GetString("department-reward-master-console-history-entry",
                ("department", entry.DepartmentName),
                ("time", entry.Entry.TimeText),
                ("text", description));
            label.SetMessage(text);
            HistoryContainer.AddChild(label);
            _historyLabels.Add(label);
            ApplyHistoryLabelWidth(label);
        }
    }

    private void OnHistoryContainerResized()
    {
        foreach (var label in _historyLabels)
            ApplyHistoryLabelWidth(label);
    }

    private void ApplyHistoryLabelWidth(RichTextLabel label)
    {
        var width = HistoryContainer.Size.X;
        if (width <= 0f && HistoryContainer.Parent is Control parent)
            width = parent.Size.X;

        if (width <= 0f)
            return;

        const float padding = 8f;
        var contentWidth = MathF.Max(0f, width - padding);
        label.MinWidth = contentWidth;
        label.MaxWidth = contentWidth;
    }

    private static string ResolveHistoryDescription(DepartmentRewardHistoryEntry entry)
    {
        var taskText = ResolveHistoryTaskTitle(entry);
        return entry.Type switch
        {
            DepartmentRewardHistoryEntryType.Completed => Loc.GetString(
                "department-reward-console-history-task-complete",
                ("task", taskText)),
            DepartmentRewardHistoryEntryType.Failed => Loc.GetString(
                "department-reward-console-history-task-failed",
                ("task", taskText),
                ("penalty", entry.Penalty ?? 0)),
            _ => entry.DescriptionFallback ?? taskText
        };
    }

    private static string ResolveHistoryTaskTitle(DepartmentRewardHistoryEntry entry)
    {
        if (!string.IsNullOrEmpty(entry.TaskTitleLocId))
            return Loc.GetString(entry.TaskTitleLocId);

        return entry.TaskTitleFallback ?? string.Empty;
    }
}
