using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy.Bank;
using Content.Shared.AWS.Economy.Bank.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Localization;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client.AWS.Economy.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyBankATMMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private EconomyBankATMBoundUserInteface Owner { get; set; }

    private EconomyBankATMAccountInfo? _bankAccount;
    private string _historyFilter = string.Empty;

    public EconomyBankATMMenu(EconomyBankATMBoundUserInteface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Owner = owner;

        SetupMoneySpinBox(WithdrawAmountBox);
        WithdrawAmountBox.ValueChanged += args =>
        {
            RefreshWithdrawButton();
        };
        WithdrawButton.OnPressed += _ => Owner.OnWithdrawPressed((ulong) WithdrawAmountBox.Value);

        SetupMoneySpinBox(TransferAmountBox);
        SetupRecipientPrefixOptions();
        TransferAmountBox.ValueChanged += args =>
        {
            RefreshTransferButton();
        };
        TransferButton.OnPressed += _ => Owner.OnTransferPressed((ulong) TransferAmountBox.Value, GetRecipientAccountId());
        TransferRecipientPrefixOption.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);
            RefreshTransferButton();
        };
        TransferRecipientNumberField.OnTextChanged += _ => RefreshTransferButton();

        HistorySearchField.OnTextChanged += _ =>
        {
            _historyFilter = HistorySearchField.Text ?? string.Empty;
            RefreshHistory();
        };
        HistorySearchField.Editable = false;

        RefreshWithdrawButton();
        RefreshTransferButton();
        RefreshAccountInfo();
    }

    public override void Close()
    {
        base.Close();
    }

    public void SetBankAcount(EconomyBankATMAccountInfo? bankAccount)
    {
        _bankAccount = bankAccount;
        var hasAccount = _bankAccount is not null;
        HistorySearchField.Editable = hasAccount;

        if (!hasAccount && !string.IsNullOrEmpty(_historyFilter))
        {
            _historyFilter = string.Empty;
            HistorySearchField.Text = string.Empty;
        }

        RefreshWithdrawButton();
        RefreshTransferButton();
        RefreshAccountInfo();
    }

    public void SetError(string? error)
    {
        ErrorLabel.Text = error;
    }

    private void RefreshWithdrawButton()
    {
        var isEnabled = _bankAccount is { } account &&
            !account.Blocked &&
            WithdrawAmountBox.Value >= 0 &&
            account.Balance >= (long) WithdrawAmountBox.Value;
        WithdrawButton.Disabled = !isEnabled;
    }

    private void RefreshTransferButton()
    {
        var isEnabled = _bankAccount is { } account &&
            !account.Blocked &&
            TransferAmountBox.Value > 0 &&
            account.Balance >= (long) TransferAmountBox.Value &&
            !string.IsNullOrWhiteSpace(GetRecipientAccountId());
        TransferButton.Disabled = !isEnabled;
    }

    private void RefreshAccountInfo()
    {
        AccountIdLabel.Text = _bankAccount?.AccountId ?? "-";
        AccountOwnerLabel.Text = _bankAccount?.AccountName ?? "-";
        AccountBalanceLabel.Text = _bankAccount?.Balance.ToString("N0") ?? "-";
        RefreshHistory();
    }

    private void SetupMoneySpinBox(SpinBox spinBox)
    {
        spinBox.AddLeftButton(-1000, "-1000");
        spinBox.AddLeftButton(-100, "-100");
        spinBox.AddLeftButton(-10, "-10");
        spinBox.AddLeftButton(-1, "-1");
        spinBox.AddRightButton(1, "+1");
        spinBox.AddRightButton(10, "+10");
        spinBox.AddRightButton(100, "+100");
        spinBox.AddRightButton(1000, "+1000");
        spinBox.IsValid = amount => amount >= 0 && _bankAccount is { } account && amount <= account.Balance;
    }

    private void RefreshHistory()
    {
        HistoryContainer.DisposeAllChildren();

        if (_bankAccount?.Logs is not { Count: > 0 } logs)
        {
            var emptyLabel = new RichTextLabel { HorizontalExpand = true };
            emptyLabel.SetMessage(Loc.GetString("economy-bank-atm-menu-history-empty"));
            HistoryContainer.AddChild(emptyLabel);
            return;
        }

        var filter = _historyFilter.Trim();
        var hasFilter = filter.Length > 0;

        foreach (var log in logs)
        {
            var timestamp = FormatLogTimestamp(log.Date);

            var entryText = Loc.GetString(
                "economy-bank-atm-menu-history-entry",
                ("time", timestamp),
                ("message", log.Text));

            if (hasFilter)
            {
                if (!timestamp.Contains(filter, StringComparison.OrdinalIgnoreCase) &&
                    !log.Text.Contains(filter, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }
            }

            var entryLabel = new RichTextLabel { HorizontalExpand = true };
            entryLabel.SetMessage(entryText);
            HistoryContainer.AddChild(entryLabel);
        }

        if (HistoryContainer.ChildCount == 0)
        {
            var noResultsLabel = new RichTextLabel { HorizontalExpand = true };
            noResultsLabel.SetMessage(Loc.GetString("economy-bank-atm-menu-history-empty-filtered"));
            HistoryContainer.AddChild(noResultsLabel);
        }
    }

    private static string FormatLogTimestamp(TimeSpan timestamp)
    {
        var totalHours = (int) Math.Floor(timestamp.TotalHours);
        return $"{totalHours:00}:{timestamp.Minutes:00}:{timestamp.Seconds:00}";
    }

    private void SetupRecipientPrefixOptions()
    {
        TransferRecipientPrefixOption.Clear();

        var prototypes = _prototypeManager.EnumeratePrototypes<EconomyBankAccountPrefixPrototype>()
            .OrderBy(p => p.Order)
            .ToList();

        if (prototypes.Count == 0)
        {
            TransferRecipientPrefixOption.AddItem(string.Empty);
            TransferRecipientPrefixOption.SetItemMetadata(0, string.Empty);
            TransferRecipientPrefixOption.SelectId(0);
            return;
        }

        var selectedIndex = 0;

        for (var i = 0; i < prototypes.Count; i++)
        {
            var proto = prototypes[i];
            var text = proto.DisplayLoc.HasValue
                ? Loc.GetString(proto.DisplayLoc.Value)
                : proto.Display ?? string.Empty;

            TransferRecipientPrefixOption.AddItem(text);
            TransferRecipientPrefixOption.SetItemMetadata(i, proto.Prefix);

            if (proto.IsDefault)
                selectedIndex = i;
        }

        TransferRecipientPrefixOption.SelectId(selectedIndex);
        RefreshTransferButton();
    }

    private string GetRecipientAccountId()
    {
        var selectedId = TransferRecipientPrefixOption.SelectedId;
        var prefix = selectedId >= 0
            ? TransferRecipientPrefixOption.GetItemMetadata(selectedId) as string ?? string.Empty
            : string.Empty;
        var number = TransferRecipientNumberField.Text?.Trim() ?? string.Empty;

        if (!string.IsNullOrEmpty(prefix) &&
            number.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
        {
            number = number[prefix.Length..];
        }

        return prefix + number;
    }
}
